# this and other docker infra adapted from: https://github.com/karlkeefer/pngr
version: '3.4'
services:
  # back-end api build
  back:
    build: 
      context: back
      target: dev
    volumes:
      - ./back:/root
    ports:
      - "5000:5000"
    env_file: ./back/.env

  # front-end build
  front:
    build: 
      context: frontend
      target: dev
    volumes:
      - ./frontend:/root
    ports:
      - "3000:3000"

  # nginx
  nginx:
    build: 
      context: nginx
      target: dev
    # image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - front
      - back
  
  #certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
