name: CD

on:
  push:
    branches:
    - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to the dev GCP server"
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/dev.key
            chmod 600 ~/.ssh/dev.key
            cat >>~/.ssh/config <<END
            Host dev 
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/dev.key
              StrictHostKeyChecking no
            END
          env:
            SSH_USER: ${{ secrets.DEV_SSH_USER }}
            SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
            SSH_HOST: ${{ secrets.DEV_SSH_HOST }}

      - name: Stop server
        run: ssh dev 'cd BrownHopeAidApp && sudo docker-compose down'
      
      - name: Checkout updates
        run: ssh dev 'cd BrownHopeAidApp && git fetch && git reset --hard origin/development'

      - name: Ensure env
        if: ${{ always() }}
        run: ssh dev 'cp .env BrownHopeAidApp/back/'
      
      - name: Restart
        if: ${{ always() }}
        run: ssh dev 'cd BrownHopeAidApp && sudo docker-compose up --build'
      
