name: CI

on:
  pull_request:
    branches:
    - development
    - production
    - ci-setup

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run frontend tests
        run: |
          cd ./frontend
          npm install
          npm test

      - name: Run backend tests
        run: |
          cd ./back
          npm install
          npm test
