name: Discord PR Notify

on:
  pull_request:
    branches: 
    - development
    - production

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sendNotification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Discord Notification
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub
          mackfoggia: Mozzia
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Pull request #{{ EVENT_PAYLOAD.pull_request.number }}: {{ EVENT_PAYLOAD.pull_request.title }} - requested by {{ EVENT_PAYLOAD.pull_request.user.login }} - {{ EVENT_PAYLOAD.pull_request.html_url }}'
